[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "NODE_ENV"
value = "production"

[[deploy.environmentVariables]]  
name = "SESSION_SECRET"
value = "sitara777-super-secret-admin-key-2024"

[[deploy.environmentVariables]]
name = "PORT"
value = "${{RAILWAY_PUBLIC_PORT}}"

# Add your Firebase credentials here after deployment
# [[deploy.environmentVariables]]
# name = "FIREBASE_PROJECT_ID"
# value = "sitara777-47f86"
# 
# [[deploy.environmentVariables]]
# name = "FIREBASE_CLIENT_EMAIL"
# value = "your-firebase-client-email"
# 
# [[deploy.environmentVariables]]
# name = "FIREBASE_PRIVATE_KEY"
# value = "your-firebase-private-key"
