class BazarModel {
  final String id;
  final String name;
  final String openTime;
  final String closeTime;
  final String? currentResult;
  final bool isOpen;
  final String iconPath;
  final List<String> gameTypes;

  BazarModel({
    required this.id,
    required this.name,
    required this.openTime,
    required this.closeTime,
    this.currentResult,
    required this.isOpen,
    required this.iconPath,
    required this.gameTypes,
  });

  static List<BazarModel> getAllBazars() {
    return [
      BazarModel(
        id: 'kalyan',
        name: 'Kalyan',
        openTime: '3:45 PM',
        closeTime: '5:45 PM',
        currentResult: '123-45-678',
        isOpen: true,
        iconPath: 'assets/icons/kalyan.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'kalyan_night',
        name: 'Kalyan Night',
        openTime: '8:20 PM',
        closeTime: '11:20 PM',
        currentResult: '456-78-901',
        isOpen: false,
        iconPath: 'assets/icons/kalyan_night.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'milan_day',
        name: 'Milan Day',
        openTime: '11:50 AM',
        closeTime: '1:50 PM',
        currentResult: '789-01-234',
        isOpen: true,
        iconPath: 'assets/icons/milan_day.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'milan_night',
        name: 'Milan Night',
        openTime: '8:50 PM',
        closeTime: '11:50 PM',
        currentResult: '012-34-567',
        isOpen: false,
        iconPath: 'assets/icons/milan_night.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'rajdhani_day',
        name: 'Rajdhani Day',
        openTime: '1:00 PM',
        closeTime: '3:00 PM',
        currentResult: '345-67-890',
        isOpen: true,
        iconPath: 'assets/icons/rajdhani_day.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'rajdhani_night',
        name: 'Rajdhani Night',
        openTime: '9:30 PM',
        closeTime: '11:30 PM',
        currentResult: '678-90-123',
        isOpen: false,
        iconPath: 'assets/icons/rajdhani_night.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'time_bazar',
        name: 'Time Bazar',
        openTime: '12:00 PM',
        closeTime: '2:00 PM',
        currentResult: '901-23-456',
        isOpen: true,
        iconPath: 'assets/icons/time_bazar.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'main_mumbai',
        name: 'Main Mumbai',
        openTime: '6:30 PM',
        closeTime: '8:30 PM',
        currentResult: '234-56-789',
        isOpen: false,
        iconPath: 'assets/icons/main_mumbai.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'main_ratan',
        name: 'Main Ratan',
        openTime: '9:20 AM',
        closeTime: '11:20 AM',
        currentResult: '567-89-012',
        isOpen: true,
        iconPath: 'assets/icons/main_ratan.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'sridevi',
        name: 'Sridevi',
        openTime: '11:55 AM',
        closeTime: '1:55 PM',
        currentResult: '890-12-345',
        isOpen: true,
        iconPath: 'assets/icons/sridevi.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'madhur_morning',
        name: 'Madhur Morning',
        openTime: '11:00 AM',
        closeTime: '1:00 PM',
        currentResult: '123-45-678',
        isOpen: true,
        iconPath: 'assets/icons/madhur_morning.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'madhuri',
        name: 'Madhuri',
        openTime: '7:15 PM',
        closeTime: '9:15 PM',
        currentResult: '456-78-901',
        isOpen: false,
        iconPath: 'assets/icons/madhuri.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'supreme_day',
        name: 'Supreme Day',
        openTime: '12:10 PM',
        closeTime: '2:10 PM',
        currentResult: '789-01-234',
        isOpen: true,
        iconPath: 'assets/icons/supreme_day.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'kuber',
        name: 'Kuber',
        openTime: '2:30 PM',
        closeTime: '4:30 PM',
        currentResult: '012-34-567',
        isOpen: true,
        iconPath: 'assets/icons/kuber.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
      BazarModel(
        id: 'kuber_express',
        name: 'Kuber Express',
        openTime: '10:15 AM',
        closeTime: '12:15 PM',
        currentResult: '345-67-890',
        isOpen: true,
        iconPath: 'assets/icons/kuber_express.png',
        gameTypes: ['Single Panna', 'Double Panna', 'Triple Panna', 'Jodi', 'Sangam', 'Motor'],
      ),
    ];
  }
}
